---
title: "CovidAnalytics"
author: "Surbhi Rathore"
date: "4/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning=FALSE}
suppressPackageStartupMessages({
library(covid19.analytics)
library(tinytex)
})
agg <- covid19.data(case = 'aggregated')
tsc <- covid19.data(case = 'ts-confirmed')
tsa <- covid19.data(case = 'ts-ALL')
tsd <- covid19.data("ts-deaths")

# obtain covid19's genomic data
covid19.gen.seq <- covid19.genomic.data()

# summary report for different locations with top 5
#report.summary(Nentries=5, geo.loc=c("US","India"))

```

```{r, echo = FALSE, warning=FALSE}
#Plots
# static and interactive plot 
totals.plt(tsa)

# totals for Ontario and Canada, without displaying totals and one plot per page
totals.plt(tsa,"India", with.totals=FALSE,one.plt.per.page=TRUE)
totals.plt(tsa,"US", with.totals=FALSE,one.plt.per.page=TRUE)

# totals for Ontario, Canada, Italy and Uruguay; including global totals with the linear and semi-log plots arranged one next to the other
totals.plt(tsa,"India", with.totals=TRUE,one.plt.per.page=FALSE)
totals.plt(tsa,"US", with.totals=TRUE,one.plt.per.page=FALSE)

# totals for all the locations reported on the dataset, interactive plot will be saved as "totals-all.html"
totals.plt(tsa, "ALL", fileName="totals-all")

#live.map(tsc)

```

```{r, echo = FALSE, warning=FALSE}
#SIR Model(semi log plot/linear log plot)
generate.SIR.model(tsc, 'US', tot.population = 328200000)
generate.SIR.model(tsc, 'India', tot.population = 136600000)

# modelling the spread for the whole world, storing the model and generating an interactive visualization
#world.SIR.model <- generate.SIR.model(data,"ALL", t0=1,t1=15, tot.population=7.8e9, staticPlt=FALSE)

# plotting and visualizing the model
#plt.SIR.model(world.SIR.model,"World",interactiveFig=TRUE,fileName="world.SIR.model")
```




Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
